//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatisation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.200")]
        public string IP_AGILENT {
            get {
                return ((string)(this["IP_AGILENT"]));
            }
            set {
                this["IP_AGILENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.210")]
        public string IP_TEKTRONIX {
            get {
                return ((string)(this["IP_TEKTRONIX"]));
            }
            set {
                this["IP_TEKTRONIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.50")]
        public string IP_IPERF_CLIENT {
            get {
                return ((string)(this["IP_IPERF_CLIENT"]));
            }
            set {
                this["IP_IPERF_CLIENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rik")]
        public string IPERFCLIENTUSER {
            get {
                return ((string)(this["IPERFCLIENTUSER"]));
            }
            set {
                this["IPERFCLIENTUSER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rik")]
        public string IPERFCLIENTPASS {
            get {
                return ((string)(this["IPERFCLIENTPASS"]));
            }
            set {
                this["IPERFCLIENTPASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int IPERFCLIENTPORT {
            get {
                return ((int)(this["IPERFCLIENTPORT"]));
            }
            set {
                this["IPERFCLIENTPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.60")]
        public string IP_IPERF_SERVER {
            get {
                return ((string)(this["IP_IPERF_SERVER"]));
            }
            set {
                this["IP_IPERF_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rik")]
        public string IPERFSERVERUSER {
            get {
                return ((string)(this["IPERFSERVERUSER"]));
            }
            set {
                this["IPERFSERVERUSER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rik")]
        public string IPERFSERVERPASS {
            get {
                return ((string)(this["IPERFSERVERPASS"]));
            }
            set {
                this["IPERFSERVERPASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int IPERFSERVERPORT {
            get {
                return ((int)(this["IPERFSERVERPORT"]));
            }
            set {
                this["IPERFSERVERPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.5")]
        public string IP_FILESERVER {
            get {
                return ((string)(this["IP_FILESERVER"]));
            }
            set {
                this["IP_FILESERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xavier")]
        public string FILESERVERUSER {
            get {
                return ((string)(this["FILESERVERUSER"]));
            }
            set {
                this["FILESERVERUSER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string FILESERVERPASS {
            get {
                return ((string)(this["FILESERVERPASS"]));
            }
            set {
                this["FILESERVERPASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int FILESERVERPORT {
            get {
                return ((int)(this["FILESERVERPORT"]));
            }
            set {
                this["FILESERVERPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.2.5")]
        public string IP_DATABASE {
            get {
                return ((string)(this["IP_DATABASE"]));
            }
            set {
                this["IP_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string MYSQL_USER {
            get {
                return ((string)(this["MYSQL_USER"]));
            }
            set {
                this["MYSQL_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string MYSQL_PASS {
            get {
                return ((string)(this["MYSQL_PASS"]));
            }
            set {
                this["MYSQL_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MYSQL_DB {
            get {
                return ((string)(this["MYSQL_DB"]));
            }
            set {
                this["MYSQL_DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int AGILENT_TIMEOUT {
            get {
                return ((int)(this["AGILENT_TIMEOUT"]));
            }
            set {
                this["AGILENT_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string NLOG_LOGFILE_LOCATION {
            get {
                return ((string)(this["NLOG_LOGFILE_LOCATION"]));
            }
            set {
                this["NLOG_LOGFILE_LOCATION"] = value;
            }
        }
    }
}
